### ISSUE TITLE
Support macOS M1

### ISSUE THREAD

**Issue by SteveL-MSFT** [jborean93/omi#47]
##### SUMMARY

Installed PSWSMan on my M1 MacBook Pro, but it complains that my system isn't macOS and it's likely because I'm on a ARM64 system

##### LIBMI VERSION

```paste below

```

**Comment by jborean93** [comment]
This should work, the latest release added support for running on aarch64. I even tested it myself. Can you share the output of `Install-WSMan -Verbose`?

**Comment by kai-h** [comment]
I too am having problems with a pure arm64 toolchain.
I can get this working on my M1 Macs if I install the Universal version of OpenSSL and then install the x86_64 versions of PowerShell and PSWSMan.

Now that I think about it, maybe Exchange Online v2 cmdlets have binary code in them? That may be the piece of the puzzle I'm missing.

Anyway, this is what I am getting:
Install MacPorts from .pkg installer
Make sure OpenSSL is installed.
`sudo port install openssl`

Install PowerShell from .pkg installer.

Launch PowerShell and install PSWSMan
```pwsh
Install-Module -Name PSWSMan
exit
```

Then, back in zsh:
`sudo pwsh -Command 'Install-WSMan'`

Back in PowerShell, install Exchange Online v2
`Install-Module -Name ExchangeOnlineManagement`

Connect to ExchangeOnline
`Connect-ExchangeOnline`
(sign in via web browser)
```
----------------------------------------------------------------------------
The module allows access to all existing remote PowerShell (V1) cmdlets in
addition to the 9 new, faster, and more reliable cmdlets.

|--------------------------------------------------------------------------|
|    Old Cmdlets                    |    New/Reliable/Faster Cmdlets       |
|--------------------------------------------------------------------------|
|    Get-CASMailbox                 |    Get-EXOCASMailbox                 |
|    Get-Mailbox                    |    Get-EXOMailbox                    |
|    Get-MailboxFolderPermission    |    Get-EXOMailboxFolderPermission    |
|    Get-MailboxFolderStatistics    |    Get-EXOMailboxFolderStatistics    |
|    Get-MailboxPermission          |    Get-EXOMailboxPermission          |
|    Get-MailboxStatistics          |    Get-EXOMailboxStatistics          |
|    Get-MobileDeviceStatistics     |    Get-EXOMobileDeviceStatistics     |
|    Get-Recipient                  |    Get-EXORecipient                  |
|    Get-RecipientPermission        |    Get-EXORecipientPermission        |
|--------------------------------------------------------------------------|

To get additional information, run: Get-Help Connect-ExchangeOnline or
check https://aka.ms/exops-docs

Send your product improvement suggestions and feedback to
exocmdletpreview@service.microsoft.com. For issues related to the
module, contact Microsoft support. Don't use the feedback alias for
problems or support issues.
----------------------------------------------------------------------------

Exception: Connecting to remote server outlook.office365.com failed with the
following error
message : error:16000069:STORE routines::unregistered scheme
For more information, see the about_Remote_Troubleshooting Help topic.
```
For the verbose messages from installing PSWSMan
```
PS /Users/kai> Install-WSMan -Verbose
VERBOSE: Failed to find brew at 'brew'
VERBOSE: Failed to find brew at '/opt/homebrew/bin/brew'
VERBOSE: Failed to find OpenSSL with homebrew, falling back to port
VERBOSE: Attempting to get OpenSSL info /opt/local/bin/port contents openssl
STDERR: 

RC: 0
VERBOSE: Checking arch information for '/opt/local/lib/libcrypto.dylib' and '/opt/local/lib/libssl.dylib'
VERBOSE: Checking if 'arm64' for '/opt/local/lib/libcrypto.dylib' is one of 'arm64'
VERBOSE: Checking if 'arm64' for '/opt/local/lib/libssl.dylib' is one of 'arm64'
VERBOSE: Port openssl libcrypto|ssl exists and is valid at '/opt/local/lib/libcrypto.dylib' and /opt/local/lib/libssl.dylib'
VERBOSE: Getting OpenSSL version for '/opt/local/lib/libssl.dylib'
VERBOSE: OpenSSL Version: Major 3 Minor 0 Patch 0
VERBOSE: Host Info:
{
  "Distribution": "macOS",
  "StandardLib": "macOS",
  "OpenSSL": "3",
  "LibCrypto": {
    "Source": "libcrypto.3.dylib",
    "Target": "/opt/local/lib/libcrypto.dylib"
  },
  "LibSSL": {
    "Source": "libssl.3.dylib",
    "Target": "/opt/local/lib/libssl.dylib"
  }
}
VERBOSE: Installing WSMan libs for 'macOS-3'
VERBOSE: Checking to see if libmi.dylib is installed
VERBOSE: Checking to see if libpsrpclient.dylib is installed
PS /Users/kai> 
```

**Comment by jborean93** [comment]
@kai-h the error you are getting is something being returned from OpenSSL. Can you try running the following:

```bash
echo "q" | openssl s_client -connect outlook.office365.com:443
```

Make sure to use the `openssl` that was installed by `port` on your host, it may be in `/opt/local/bin/openssl` but I'm unsure where `port` installs binaries to.

Could you also run `$Error[0] | Select *` and `$Error[0].Exception.ToString()` after trying to connect and share the results. This will help try and track down whether the problem is trying to connect through WSMan or maybe something else in `ExchangeOnlineManagement`, i.e. getting the OAuth token or something else unrelated to OMI.

The only 2 things I could find that seemed anyway related to that OpenSSL error are https://github.com/openssl/openssl/issues/14622 and https://github.com/openssl/openssl/issues/16167. They don't seem to indicate what may be the problem in your case but they definitely get the same error. The error is coming from https://github.com/openssl/openssl/blob/7a2ad00f3ecffa6be350e9e72992d4ec003f54ae/crypto/store/store_register.c#L214-L273 but I'm unsure how it all relates to what is happening here.

**Comment by kai-h** [comment]
Here's the info requested - and once again I must thank you for your dedication to getting this working.
First up is the info re: OpenSSL. Below this will be the full output including more information on the error.
```
kai@hobbes ~ % which openssl
/opt/local/bin/openssl
kai@hobbes ~ % echo "q" | openssl s_client -connect outlook.office365.com:443
CONNECTED(00000006)
depth=1 C = US, O = DigiCert Inc, CN = DigiCert Cloud Services CA-1
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, CN = outlook.com
verify return:1
---
Certificate chain
 0 s:C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, CN = outlook.com
   i:C = US, O = DigiCert Inc, CN = DigiCert Cloud Services CA-1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jul  2 00:00:00 2020 GMT; NotAfter: Jul  2 12:00:00 2022 GMT
 1 s:C = US, O = DigiCert Inc, CN = DigiCert Cloud Services CA-1
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep 25 00:00:00 2020 GMT; NotAfter: Sep 24 23:59:59 2030 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIItDCCB5ygAwIBAgIQC7z+7VKeW8eQt7ugP4I7EDANBgkqhkiG9w0BAQsFADBL
-- snip --
2tqxdsG9Y2vbN7bzKMx8aPr15+ngteMr
-----END CERTIFICATE-----
subject=C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, CN = outlook.com
issuer=C = US, O = DigiCert Inc, CN = DigiCert Cloud Services CA-1
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: ECDH, secp384r1, 384 bits
---
SSL handshake has read 4013 bytes and written 485 bytes
Verification error: unable to get local issuer certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 87490000C1E8E927207C02CC006315D7AB1C10FC93EA2F5F9959030A3FDD03A6
    Session-ID-ctx: 
    Master-Key: B74DBF457298F6CE0F7C9E2C92F9C25E2747BBF1A4A609B241EFA6A0B5FB093243A6F7E2BE999039745B1062410DF592
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1639204771
    Timeout   : 7200 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
    Extended master secret: yes
---
DONE
kai@hobbes ~ % pwsh
PowerShell 7.2.0
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /Users/kai> Connect-ExchangeOnline

----------------------------------------------------------------------------
The module allows access to all existing remote PowerShell (V1) cmdlets in addition to the 9 new, faster, and more reliable cmdlets.

|--------------------------------------------------------------------------|
|    Old Cmdlets                    |    New/Reliable/Faster Cmdlets       |
|--------------------------------------------------------------------------|
|    Get-CASMailbox                 |    Get-EXOCASMailbox                 |
|    Get-Mailbox                    |    Get-EXOMailbox                    |
|    Get-MailboxFolderPermission    |    Get-EXOMailboxFolderPermission    |
|    Get-MailboxFolderStatistics    |    Get-EXOMailboxFolderStatistics    |
|    Get-MailboxPermission          |    Get-EXOMailboxPermission          |
|    Get-MailboxStatistics          |    Get-EXOMailboxStatistics          |
|    Get-MobileDeviceStatistics     |    Get-EXOMobileDeviceStatistics     |
|    Get-Recipient                  |    Get-EXORecipient                  |
|    Get-RecipientPermission        |    Get-EXORecipientPermission        |
|--------------------------------------------------------------------------|

To get additional information, run: Get-Help Connect-ExchangeOnline or check https://aka.ms/exops-docs

Send your product improvement suggestions and feedback to exocmdletpreview@service.microsoft.com. For issues related to the module, contact Microsoft support. Don't use the feedback alias for problems or support issues.
----------------------------------------------------------------------------

Exception: Connecting to remote server outlook.office365.com failed with the following
error message : error:16000069:STORE routines::unregistered scheme For more
information, see the about_Remote_Troubleshooting Help topic.

PS /Users/kai> $Error[0] | Select * and $Error[0].Exception.ToString()
Select-Object: A positional parameter cannot be found that accepts argument 'and'.
PS /Users/kai> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Darwin 21.1.0 Darwin Kernel Version 21.1.0: Wed…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /Users/kai> 
```

**Comment by kai-h** [comment]
And, I don't know if this info is more useful feedback on the error:
```
PS /Users/kai> $Error[0].Exception.ToString()
System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server outlook.office365.com failed with the following error message : error:16000069:STORE routines::unregistered scheme For more information, see the about_Remote_Troubleshooting Help topic.
   at Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSession.HandleError(PSDataCollection`1 errors)
   at Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSession.ExecutePsCommand(PSCommand command)
   at Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSession.ProcessNewConnection()
   at Microsoft.Exchange.Management.ExoPowershellSnapin.NewExoPSSession.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
PS /Users/kai> 
```

**Comment by jborean93** [comment]
Thanks for the info, I'll have to spin up my mac mini to try it out and see if I can track down some more information. Thanks for sharing the exception traceback as it definitely shows it's part of the WSMan/OMI operations that's causing the error.

**Comment by jborean93** [comment]
I've spun up my M1 box and I've found that OpenSSL 3 from `brew` works just fine but OpenSSL 3 from `port` fails with the same error you see.

Both versions are the arm64 variant as confirmed by `lipo -archs <dylib>` and both the versions show `OpenSSL 3.0.0 7 sep 2021 (Library: OpenSSL 3.0.0 7 sep 2021)`. When comparing the `openssl s_client` commands I can see that `brew` trusts the certificate whereas `port` does not (you can see that in your output as well).

### Port

```bash
echo "y" | /opt/local/bin/openssl s_client -connect outlook.office365.com:443

---SNIP---
-----END CERTIFICATE-----
subject=C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, CN = outlook.com
issuer=C = US, O = DigiCert Inc, CN = DigiCert Cloud Services CA-1
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: ECDH, secp384r1, 384 bits
---
SSL handshake has read 4292 bytes and written 485 bytes
Verification error: unable to get local issuer certificate
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 14A1714DAEB255323F4FC677863DB0412844A93DA73FC10097ED697A531BC6DE
    Session-ID-ctx:
    Master-Key: CDAA35544F2362C8AC0A13E06AAAEEB5986E98D16A77F170CE6E6DBF87EB93D66C16ABB14E16C165E976241D724CA290
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 36000 (seconds)
    TLS session ticket:
    0000 - 00 00 00 00 e6 ff 9b 3c-1e 01 ce 4a b6 77 01 08   .......<...J.w..
    0010 - 10 1f 86 99 26 c2 25 34-21 25 ad 93 6d ba 6c 66   ....&.%4!%..m.lf
    0020 - 40 b7 c3 38 c5 8f 1b da-24 7f 10 fa 77 56 d0 5c   @..8....$...wV.\
    0030 - 24 81 5b f1 5c 2c 5e 44-77 2f d4 5b 8b 22 f3 0b   $.[.\,^Dw/.[."..
    0040 - 17 3e c4 40 8b ce 93 20-1c 22 e0 9e ba 9f 19 6c   .>.@... .".....l
    0050 - a1 35 9f 2e 9a a2 1c 22-c7 ee d1 31 9b 6e 22 8d   .5....."...1.n".
    0060 - 17 e8 ad 20 10 57 9b 11-28 e1 d9 ba 37 c3 f1 11   ... .W..(...7...
    0070 - 60 6d 43 fe fc 39 11 57-30 cf a4 62 65 23 11 ed   `mC..9.W0..be#..
    0080 - 77 e9 9d 5f f6 db 6f a0-22 fe d6 3a 6b 14 d3 db   w.._..o."..:k...
    0090 - 9c c9 f4 f2 6e 65 d6 de-ed 83 5b a1 f6 55 17 35   ....ne....[..U.5
    00a0 - a0 63 32 81 be aa 29 9e-8e b7 04 70 53 49 36 c3   .c2...)....pSI6.
    00b0 - 17 4a f2 f0 c4 3f 36 1d-a1 a9 68 33 e9 d3 b1 b1   .J...?6...h3....
    00c0 - 2b 42 0b 7f c9 7f c2 94-ca 6c d7 36 f7 9e b8 58   +B.......l.6...X
    00d0 - 5a d7 81 77 6c 06 b2 c5-2b 45 a6 e3 b0 46 9e 5b   Z..wl...+E...F.[
    00e0 - 5b f6 22 08 b6 bd fd 1b-e4 c9 a9 f6 47 2a ce 00   [.".........G*..
    00f0 - 95 a3 b0 7d 1d d4 e8 94-31 23 da b0 b6 84 f1 32   ...}....1#.....2
    0100 - ff 89 f4 a7                                       ....

    Start Time: 1639365592
    Timeout   : 7200 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
    Extended master secret: yes
---
DONE
```

### Brew

```bash
echo "y" | /opt/homebrew/opt/openssl@3/bin/openssl s_client -connect outlook.office365.com:443

---SNIP---
-----END CERTIFICATE-----
subject=C = US, ST = Washington, L = Redmond, O = Microsoft Corporation, CN = outlook.com
issuer=C = US, O = DigiCert Inc, CN = DigiCert Cloud Services CA-1
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: ECDH, secp384r1, 384 bits
---
SSL handshake has read 4013 bytes and written 485 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: A13300002795FCFF62BD4BD993C56C4D2EDF6CD7D7E695BF0F34D90E3284421B
    Session-ID-ctx:
    Master-Key: DD85539329552B15B13F709CA2274CC107AD29F0EBCC774001A286B6C8B6E7D796038EE77F4219270B7D6E16895D6FF7
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1639365582
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---
DONE
```

Note how `port` has `Verify return code: 20 (unable to get local issuer certificate)`. Typically an error around cert validation from OMI will be a message that contains `certificate verify failed` but in this case it seems like however `port` is configured means it will return this particular error. I've also verified this by trying to connect to a target with a self signed certificate when using the `port` provided OpenSSL libs. When installing the [curl-ca-bundle](https://ports.macports.org/port/curl-ca-bundle/summary/) package with `port` then things started working when targeting Exchange Online and the `s_client` command shows a successful verification just like `brew`.

![image](https://user-images.githubusercontent.com/8462645/145748107-f5e00aff-5026-42e4-950a-850ab289e145.png)

Why this package is not installed at `openssl` I have no idea and why OpenSSL itself did not provide a better error message here is beyond my abilities. Ultimately in the end both `port` and `brew` work just fine on an M1 macOS install. You just need to ensure:

* The architecture of OpenSSL is either `universal` or matches the arch of the `pwsh` that is running
* A valid certificate bundle is set up and configured
  * Seems like `brew` does this automatically but for `port` you either need to install `curl-ca-bundle` or configure it manually

I'll update the docs to mention `curl-ca-bundle` to help others who may be using that but unfortunately there isn't must more I can do here.

@SteveL-MSFT are you still having troubles getting this to work on your M1 host? If so can you run `Install-WSMan -Verbose` to get more information around the OpenSSL versions that were searched and why they were excluded from the final install.

**Comment by jborean93** [comment]
https://github.com/jborean93/omi/pull/48 expands on the docs somewhat to cover this scenario.

**Comment by kai-h** [comment]
Amazing. That has fixed it, and now I have a 100% native M1 toolchain to administer Office 365 via PowerShell.
Thank you so much for digging into this. Can I buy you a beer for your efforts?
I'll update the instructions on my blog as well.

**Comment by jborean93** [comment]
Glad it solved the problem for you. No need for beer, I'm just happy the problem can be solved.
